
services:
  frontend:
    build: ./frontend
    image: src/frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_BACKEND_URL: "http://backend:3000"
    ports:
      - "3000:3000"
    container_name: itcross-frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]  
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  backend:
    build: ./backend
    image: src/backend
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3001:3000"
    container_name: itcross-backend
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health_backend"]  
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

