version: '3.8'

services:
  frontend:
    build: ./frontend
    image: src/frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_BACKEND_URL: "http://backend:8000"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    container_name: itcross-frontend

  postgres:
    image: postgres:13
    user: "${UID}:${GID}" 
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d  
    ports:
      - "5432:5432"
    container_name: itcross-postgres

  backend:
    build: ./backend
    image: src/backend
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    container_name: itcross-backend
